// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Logixware.SoftEther.Client.Manager
{
	public partial class ConnectionsViewController : NSViewController
	{
		public ConnectionsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
