// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Logixware.SoftEther.Client.Manager
{
	public partial class InterfacesViewController : NSViewController
	{
		public InterfacesViewController (IntPtr handle) : base (handle)
		{
//			this.InterfacesTableView.Ite
        }

        partial void InterfacesTableViewChanged(AppKit.NSTableView sender)
        {
            Console.WriteLine("");
        }
	}
}
