  // This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Linq;
using CoreGraphics;

namespace Logixware.SoftEther.Client.Manager
{
	public partial class MainWindowController : NSWindowController
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

		public override void WindowDidLoad()
		{
			base.WindowDidLoad();
			base.Window.TitleVisibility = NSWindowTitleVisibility.Hidden;
		}

		partial void SectionSelectorChanged(AppKit.NSSegmentedControl sender)
		{
			var __MainViewController = (MainViewController)this.ContentViewController;

			if (this.SectionSelector.SelectedSegment == 0)
			{
				__MainViewController.DisplayView(Views.Connections);
			}
			else
			{
				__MainViewController.DisplayView(Views.Interfaces);
			}
		}
	}
}
